# Generated by Django 4.0.6 on 2022-10-11 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=250)),
                ('body', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=50)),
                ('image_template', models.ImageField(upload_to='assets')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('background_image', models.ImageField(default='background/default-background.jpg', upload_to='backgrounds')),
                ('qualified', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sticker_image', models.ImageField(default='stickers/default-sticker.jpg', upload_to='stickers')),
                ('slot', models.IntegerField()),
                ('rarity_category', models.CharField(choices=[('Común', 'Común'), ('Épica', 'Épica'), ('Legendaria', 'Legendaria')], max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppQatarWC2022.country')),
            ],
        ),
        migrations.CreateModel(
            name='LogoSticker',
            fields=[
                ('sticker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AppQatarWC2022.sticker')),
            ],
            bases=('AppQatarWC2022.sticker',),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField()),
                ('avatar_image', models.ImageField(default='avatars/default-avatar.jpg', upload_to='avatars')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppQatarWC2022.country')),
                ('internal_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSticker',
            fields=[
                ('sticker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AppQatarWC2022.sticker')),
                ('birthdate', models.DateField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppQatarWC2022.playerposition')),
            ],
            bases=('AppQatarWC2022.sticker',),
        ),
        migrations.CreateModel(
            name='GeneratedSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker_category', models.CharField(choices=[('New', 'New'), ('Glued', 'Glued'), ('Swapped', 'Swapped')], max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppQatarWC2022.userprofile')),
                ('sticker_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppQatarWC2022.playersticker')),
            ],
        ),
    ]
