# Generated by Django 4.0.6 on 2022-09-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatarWC2022', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='basura_intergalactica',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_image',
            field=models.ImageField(default='avatars/default_avatar.jpg', upload_to='avatars'),
        ),
    ]
