# Generated by Django 4.0.6 on 2022-10-11 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppQatarWC2022', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=250)),
                ('body', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='assets')),
            ],
        ),
        migrations.DeleteModel(
            name='StackCategory',
        ),
        migrations.RemoveField(
            model_name='playerposition',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='country',
            name='background_image',
            field=models.ImageField(default='background/default-background.jpg', upload_to='backgrounds'),
        ),
        migrations.AlterField(
            model_name='generatedsticker',
            name='sticker_category',
            field=models.CharField(choices=[('New', 'New'), ('Glued', 'Glued'), ('Swapped', 'Swapped')], max_length=50),
        ),
        migrations.AlterField(
            model_name='playersticker',
            name='sticker_image',
            field=models.ImageField(default='stickers/default-sticker.jpg', upload_to='stickers'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_image',
            field=models.ImageField(default='avatars/default-avatar.jpg', upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='internal_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
