# Generated by Django 4.0.6 on 2022-09-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatarWC2022', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='PlayerCard',
        ),
    ]
