# Generated by Django 4.0.6 on 2022-09-26 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatarWC2022', '0002_alter_userprofile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='playersticker',
            name='sticker_image',
            field=models.ImageField(default='stickers/default_sticker.jpg', upload_to='stickers'),
        ),
        migrations.AlterField(
            model_name='playersticker',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppQatarWC2022.playerposition'),
        ),
    ]
