# Generated by Django 4.0.6 on 2022-10-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatarWC2022', '0002_remove_generatedsticker_sticker_template_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sticker',
            old_name='name',
            new_name='full_name',
        ),
    ]
