# Generated by Django 4.0.6 on 2022-10-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatarWC2022', '0002_article_delete_stackcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='image_template',
        ),
    ]
