# Generated by Django 4.0.6 on 2022-09-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatarWC2022', '0002_player_delete_playercard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='PlayerCard',
        ),
    ]
