# Generated by Django 4.0.6 on 2022-09-22 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppQatarWC2022', '0003_rename_player_playercard'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('basura_intergalactica', models.CharField(max_length=50)),
                ('internal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='PlayerCard',
            new_name='PlayerSticker',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
