# Generated by Django 4.0.6 on 2022-10-11 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppQatarWC2022', '0003_rename_name_sticker_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='full_name',
        ),
    ]
