# Generated by Django 4.0.6 on 2022-10-11 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppQatarWC2022', '0004_rename_name_country_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_read', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='AppQatarWC2022.userprofile')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='AppQatarWC2022.userprofile')),
            ],
        ),
    ]
